# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:year/:month/:day/:title/
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: www.chrisyin.com/
# baseurl: /sustain/
title: Chris Yin
author: Chris Yin
description: Personal blog
avatar: profile.png
email: christopher.e.yin@gmail.com
twitter: chriseyin
linkedin: chrisyin
instagram: chriseyin
facebook: chriseyin
tumblr: chriseyin
# Comment out if you don't want disqus 
disqus: chrisyin
google_analytics: UA-35234352-1


# needed for travis-ci build
exclude: [vendor]
