# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://username.github.io/
# baseurl: /sustain/
title: Chris Yin
author: Chris Yin
description: Personal blog
avatar: profile.png
email: christopher.e.yin@gmail.com
github: chrisyin # username
twitter: chriseyin
linkedin: chrisyin
stackoverflow: chriseyin   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: chriseyin
google_analytics: UA-35234352-1


# needed for travis-ci build
exclude: [vendor]
